name: daggerito
description: IoC container with Dagger like abstractions (dependency injection with Components, SubComponents, Modules), supports components collaboration, singletons, tagging.
version: 1.0.6
author: Siddik Nazdrajic <s.nazdrajic@gmail.com>
homepage: https://github.com/sidinaz/daggerito
environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  test:
