name: daggerito
description: IoC container with Dagger like abstractions (dependency injection with Components, SubComponents, Modules), supports components collaboration, singletons, tagging.
version: 1.0.8
author: Siddik Nazdrajic <s.nazdrajic@gmail.com>
homepage: https://github.com/sidinaz/daggerito
environment:
  sdk: ">=2.6.0 <3.0.0"

dev_dependencies:
  test: ">=1.9.0 <2.0.0"
